# Generated by Django 3.0 on 2023-04-20 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
    ]
